### ISSUE TITLE
Missing lm checkpoint

### ISSUE THREAD

**Issue by spilioeve** [rowanz/piglet#1]
Hey! I am trying to download the checkpoint for the trained lm (in the description you say it is under gs://piglet/checkpoints/language_model/model.ckpt-20000). However, this is not a valid path; I downloaded the contents under gs://piglet/checkpoints/language_model and I could only find the *.index, *.data-00000-of-000001 and *.meta files. 

Please lmk if I am missing something or the files are provided somewhere else. Essentially I want to experiment with the predict_statechange part of the project and different ways to fine-tune in the NLU task, so I would prefer to avoid re-training the entire LM. I am also trying to run the finetune_sc.py file, would it be possible to point me to the yaml config file? I found two versions (flagship_configs and symbol2text_configs), but I am not sure about the paths or what some of the params mean ("train_time_symbolic_actions_prob", "fuse_action",). Thank you!

**Comment by rowanz** [comment]
hi there! sorry for any confusion. The name "gs://piglet/checkpoints/language_model/model.ckpt-20000" just refers to the three files you downloaded: 

gs://piglet/checkpoints/language_model/model.ckpt-20000.data-00000-of-00001
gs://piglet/checkpoints/language_model/model.ckpt-20000.index
gs://piglet/checkpoints/language_model/model.ckpt-20000.meta

so you should be all set! For the configuration you'd want to use [this file](https://github.com/rowanz/piglet/blob/main/model/predict_statechange/flagship_configs/base.yaml) as the starting point (for predicting state change from text).

Sorry for any confusion with parameters too. 

- `train_time_symbolic_actions_prob` is whether you want to possibly feed the model the symbolic representation of each action (e.g. `<cook, Egg>`) versus a natural language text representation (e.g. "The robot cooks the egg.") - [code is here](https://github.com/rowanz/piglet/blob/41fb35a3606415deabb47541e59d9d286c398350/model/predict_statechange/finetune_sc.py#L97). so you probably want to set that to 0.0 (i think that's what I used in the paper.)
- `fuse_action` refers to whether we should predict "what happens next" to both objects jointly, or separately -- [see here](https://github.com/rowanz/piglet/blob/41fb35a3606415deabb47541e59d9d286c398350/model/interact/modeling.py#L382). I found in the paper that using this context helps quite a bit, so I'd recommend turning it on :)

hope that helps!

**Comment by spilioeve** [comment]
Hi! Thank you for your reply, this is extremely helpful! :) 

I still have a minor question; which of these three model files should the "init_checkpoint" and "interact_checkpoint" params of the yaml config point to?

**Comment by rowanz** [comment]
no worries! `init_checkpoint` should be the LM checkpoint, and `interact_checkpoint`  should be for the physical interaction checkpoint which is here: `gs://piglet/checkpoints/physical_dynamics_model/model.ckpt-5420`. I handled them [here](https://github.com/rowanz/piglet/blob/41fb35a3606415deabb47541e59d9d286c398350/model/predict_statechange/finetune_sc.py#L240) if it helps 😄

**Comment by spilioeve** [comment]
Awesome, thank you! :)
