### ISSUE TITLE
downloading tfrecords: non-free?

### ISSUE THREAD

**Issue by nilinykh** [rowanz/piglet#2]
Hello,
thank you for the amazing work!

So, if I want to download tfrecords, do I have to pay some money for them? Or is it free, but the reason why 'requester pays' is on is because otherwise google cloud would not allow to upload these files into their system?

**Comment by rowanz** [comment]
hi there!

It's the former. (I was worried about making them public in case someone was to download them thousands of times though).

that said, if that's a barrier to entry, let me know and we can figure out another way for you to get the data 😄

**Comment by nilinykh** [comment]
I have contacted you via e-mail, perhaps, we should discuss it there? Thanks =)
